spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enjoy4
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      secret-key: 14290291d47c678b771a4bfa5795117661a1684351e710d319734bd5695eeb79
      expiration: 30000 # 30 sec en ms
      cookie-name: jwt-cookie
      refresh-token:
        expiration: 1296000000 # 15 jours en ms
        cookie-name: refresh-jwt-cookie


